apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: build-and-push-kaniko
spec: 
  workspaces:
    - name: source 
  params:
    - name: CONTEXT
      description: image's context root path 
      default: "."
    - name: IMAGE
      description: image name 
      default: docker.io/nexweb1/nodejs
    - name: imageTag 
      description: image tag
      default: dev
    - name: tlsVerify 
      default: "true"
    - name: DOCKERFILE 
      default: "./app/nodejs/Dockerfile"
    - name: FORMAT
      default: "oci"
    - name: verbose 
      default: "true"
  steps:
  - name: build-and-push-kaniko
    workingDir: $(workspaces.source.path)
    image: gcr.io/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    - name: IMAGE_DIGEST 
      value: 
    command:
    - /kaniko/executor
    - --dockerfile=$(params.DOCKERFILE)
    - --context=$(workspaces.source.path)/$(params.CONTEXT)  # The user does not need to care the workspace and the source.
    - --destination=$(params.IMAGE)
    - --oci-layout-path=$(workspaces.source.path)/$(params.CONTEXT)/image-digest
    volumeMounts:
      - name: kaniko-secret
        mountPath: /tekton/home/.docker
  volumes:
    - name: kaniko-secret 
      secret: 
        secretName: docker-credentials 
        items: 
          - key: .dockerconfigjson 
            path: config.json


