apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: build-push-task-run-
spec:
  serviceAccountName: default
  params:
    - name: DOCKERFILE
      value: "./app/nodejs/Dockerfile"
  taskRef:
    name: kaniko
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: my-source-pvc

      

