apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-user00-task
spec:
    resources:
      inputs:
        - name: source
          type: git
      outputs:
        - name: image
          type: image
    steps:
      - name: build-and-push
        image: gcr.io/kaniko-project/executor
        workingDir: /workspace/source        
        command:
          - /kaniko/executor
        args:
          - --destination=$(resources.outputs.image.url)
          - --dockerfile=app/nodejs/Dockerfile
          - --context=$(resources.inputs.source.path)/.
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
    volumes:
      - name: kaniko-secret
        secret:
          secretName: dockerhub-user00-credentials
          items:
            - key: .dockerconfigjson
              path: config.json

