apiVersion: tekton.dev/v1beta1
kind: Pipeline 
metadata:
  name: nodejs-pipeline
spec: 
  params:
    - name: IMAGE
      description: Image description
      type: string
      default: "docker.io/nexweb1/nodejs-app"
    - name: TAG
      description: Preferred tag
      default: latest
    - name: gitUrl
      description: my nodejs demo
      default: "https://gitlab.com/nexweb/tekton-handson"
    - name: DOCKERFILE
      description: Dockerfile path
      default: "./app/nodejs/Dockerfile"
  workspaces:
    - name: source
    - name: docker-credentials
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.gitUrl)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-and-push
      taskRef:
        name: kaniko
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: docker-credentials  
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)"
        - name: CONTEXT
          value: "."
        - name: FORMAT
          value: "docker"
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
    - name: create-deployment
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-and-push
      params:
        - name: script
          value: |
            kubectl apply --filename app/nodejs/deployment.yml
      workspaces:
        - name: manifest-dir
          workspace: source   