apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv 
  labels:
    type: local
spec:
  capacity: 
    storage: 100Mi
  accessModes:
     - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/tmp"
    type: Directory
