apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: education
spec:
  params:
    - default: 'https://gitlab.com/nexweb/sample-service.git'
      description: Git repository url
      name: gitUrl
      type: string
    - default: msa
      description: Git revision to check out
      name: gitRevision
      type: string
    - default: src
      description: 'The path to the build context, used by Kaniko - within the workspace'
      name: pathToContext
      type: string
    - default: docker.io/nexweb1/sample
      description: Image name including repository
      name: IMAGE
      type: string
    - default: latest
      description: Image tag
      name: imageTag
      type: string
    - default: deployment/deployment.yaml
      description: The path to the yaml file to deploy within the git source
      name: pathToYamlFile
      type: string
    - default: sample
      name: APP_NAME
      type: string
  tasks:
    - name: clone-repo
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build-maven
      runAfter:
        - clone-repo
      taskRef:
        kind: Task
        name: build-maven
      workspaces:
        - name: source
          workspace: source
    - name: build-and-push
      params:
        - name: IMAGE
          value: docker.io/nexweb1/sample
        - name: IMAGE_TAG
          value: latest
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:ac0b8714cc260c94435cab46fe41b3de0ccbc3d93e38c395fa9d52ac49e521fe
        - name: DOCKERFILE
          value: deployment/Dockerfile
        - name: tlsVerify
          value: 'true'
      runAfter:
        - build-maven
      taskRef:
        kind: Task
        name: build-and-push
      timeout: 2m0s
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    - name: deploy
      params:
        - name: SCRIPT
          value: |
            oc new-app --name=$(params.APP_NAME) \
              --docker-image=$(params.IMAGE) \
              --as-deployment-config \
              -n education-dev
      runAfter:
        - build-and-push
      taskRef:
        kind: Task
        name: deploy
      workspaces:
        - name: manifest-dir
          workspace: source
  workspaces:
    - name: source
    - name: dockerconfig