apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
  namespace: education
spec:
  description: >-
    This task runs commands against the cluster provided by user and if not
    provided then where the Task is being executed.

    OpenShift is a Kubernetes distribution from Red Hat which provides oc, the
    OpenShift CLI that complements kubectl for simplifying deployment and
    configuration applications on OpenShift.
  params:
    - default: oc help
      description: The OpenShift CLI arguments to run
      name: SCRIPT
      type: string
    - default: latest
      description: The OpenShift Version to use
      name: VERSION
      type: string
  steps:
    - env:
        - name: HOME
          value: /tekton/home
      image: >-
        image-registry.openshift-image-registry.svc:5000/openshift/cli:$(params.VERSION)
      name: oc
      resources: {}
      script: >
        #!/usr/bin/env bash


        SECRET=$(oc get secrets | grep k5-admin-sa |grep cluster |awk '{print
        $1}')


        TOKEN_DATA=$(oc get secret $SECRET -o jsonpath='{.data.token}')


        TOKEN=$(echo ${TOKEN_DATA} | base64 -d)

        echo "Deploy..."

        ls -al

        oc login --token=$TOKEN
        --server=https://api.openshift-01.knowis.cloud:6443


        $(params.SCRIPT)
      securityContext:
        privileged: true
        runAsUser: 0
      workingDir: $(workspaces.manifest-dir.path)
  workspaces:
    - description: >-
        The workspace which contains kubernetes manifests which we want to apply
        on the cluster.
      name: manifest-dir