apiVersion: tekton.dev/v1beta1 
kind: Task
metadata:
  name: read-task
spec:
  # params:
  resources:
    inputs:
        - name: workspace
          type: git
  steps:
    - name: build-sources
      image: ubuntu
      command:
        - /bin/bash
      args: ["cat README.md"]
