apiVersion: tekton.dev/v1beta1
kind: Task 
metadata:
  name: initial-task
spec: 
  workspaces:
    - name: task-ws 
      description:  The folder where we write the message to
  steps:
    - name: initial-task
      image: alpine 
      script: |
        #!/bin/sh 
        echo "Starting initial task"
        echo "Hello World!" > $(workspaces.task-ws.path)/message.txt
        ls -la $(workspaces.task-ws.path)

        
