apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: read-task-run
spec:
  resources:
    inputs:
      - name: workspace 
        resourceRef:
          name: nodejs-source
  taskRef:
    name: read-task
