apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: overlay
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: tlsVerify 
      default: "true"      
    - name: IMAGE_PUSH_SECRET_NAME
      description: Kubernetes secrets contain image push username and password
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable
      workingDir: $(workspaces.source.path)
      script: |
        buildah bud --tls-verify=$(params.tlsVerify) \
          --no-cache -f $(params.DOCKERFILE) -t $(params.IMAGE) .
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
    - name: push
      image: quay.io/buildah/stable
      workingDir: $(workspaces.source.path)
      script: |
        buildah push --tls-verify=$(params.tlsVerify) \
          $(params.IMAGE)
      volumeMounts:
        - name: docker-secret 
          mountPath: /tekton/home/.docker
        - name: varlibcontainers
          mountPath: /var/lib/containers
      securityContext:
        privileged: true
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: docker-secret
      secret: 
        secretName: docker-credentials 
        items: 
          - key: .dockerconfigjson 
            path: config.json      