apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: java-pipeline
  serviceAccountName: docker-login
  timeout: 3m
  params:
  - name: buildRevision
    value: 'prod'
  - name: appGitUrl
    value: 'https://gitlab.com/nexweb/sample-service.git'
  - name: appGitRevision
    value: hello
  - name: configGitUrl
    value: 'https://gitlab.com/nexweb/sample-service-deploy.git'
  - name: IMAGE
    value: 'docker.io/nexweb1/sample'
  - name: deployYamlFile
    value: deployment/sample.yaml
  - name: configGitRevision
    value: main
  - name: argoAppName
    value: sample    
  workspaces:
  - name: maven-settings
    configMap:
      name: custom-maven-settings
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: pipeline-pvc
  