apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitops-pipeline
spec:
  params:
    - name: appGitUrl
      description: app git repository
    - name: appGitRevision
      description: Branch Name of appGit
      default: hello
    - name: configGitUrl
      description: manifest git repository url
    - name: IMAGE
      description: Image description
      type: string
      default: "docker.io/nexweb1/sample"
    - name: TAG
      description: Preferred tag
      default: latest
    - name: buildRevision
      description: Image tag
    - name: deployYamlFile
      description: manifest file
      default: deployment/sample.yaml
    - name: configGitRevision
      description: Branch Name of configGit
      default: main      
    - name: argoAppName
      description: argo app name 
      default: sample
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.appGitUrl)"
        - name: revision
          value: hello
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: build-maven-v2
      runAfter:
        - fetch-repository
      params:
        - name: MAVEN_MIRROR_URL
          value: http://repo1.maven.org/maven2
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
      
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
    - name: list-directory
      taskRef:
        name: list-directory
      runAfter:
        - maven-run
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - list-directory
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.buildRevision)"
        - name: DOCKERFILE
          value: deployment/Dockerfile
    - name: update-manifest
      taskRef:
        name: update-yaml
      params:
        - name: IMAGE
          value: $(params.IMAGE) 
        - name: buildRevision 
          value: $(params.buildRevision)
        - name: contextPath 
          value: "."
        - name: pathToYamlFile
          value: $(params.deployYamlFile)
        - name: argo-app-name
          value: $(params.argoAppName)
        - name: url
          value: $(params.configGitUrl)
        - name: revision
          value: $(params.configGitRevision)
      runAfter:
        - build-push-image
      workspaces:
        - name: output
          workspace: shared-workspace