apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn
spec:
  workspaces:
  - name: maven-repo
  params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["clean", "package"]
  resources:
    inputs:
    - name: source
      type: git
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: /workspace/source
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(params.GOALS)"
    - name: target-file-list 
      image: alpine
      workingDir: /workspace/source
      script: |
        #!/bin/sh 
         echo "-----------------------------------------------------------------------"
         echo "                          maven target output                          " 
         echo "-----------------------------------------------------------------------"
        pwd
        ls -al target
   

