apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-source
spec:
  type: git 
  params: 
    - name: revision 
      value: main 
    - name: url 
      value: https://gitlab.com/nexweb/handson-tekton.git 
