apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: pipeline-to-list-files
spec: 
  resources:
    - name: appSource 
      type: git 
  params:
    - name: path 
      description: A File is location.
      default: README.md
  tasks: 
    - name: list-files 
      taskRef:
        name: task-to-list-files 
      resources:
        inputs:
          - name: pipeline-git 
            resource: appSource