apiVersion: tekton.dev/v1beta1 
kind: PipelineRun 
metadata:
  generateName: pipelinerun-to-list-files-
spec: 
  resources:
    - name: appSource 
      resourceRef:
        name: nodejs-source
  pipelineRef:
    name: pipeline-to-list-files 