apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-to-list-files
spec: 
  resources:
    inputs:
      - name: pipeline-git
        type: git
  steps:
    - name: list 
      image: ubuntu 
      command:
        - bash 
      args: 
        - -c 
        - |
          ls -al $(resources.inputs.pipeline-git.path) 
