apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: goodbye-user00
spec:
  steps:
    - name: goodbye 
      image: alpine 
      script: |
        #!/bin/sh
        echo "Goodbye World!" 
      
        