apiVersion: tekton.dev/v1beta1 
kind: TaskRun
metadata:
  name: initial-task-run
spec:
  taskRef:
    name: initial-task
  workspaces:
    - name: task-ws 
      persistentVolumeClaim:
        claimName: my-pvc

        