apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
spec:
  params:
  - default: .
    description: image's context root path
    name: CONTEXT
    type: string
  - default: docker.io/nexweb1/nodejs
    description: image name
    name: IMAGE
    type: string
  - default: "true"
    name: tlsVerify
    type: string
  - default: Dockerfile"
    name: DOCKERFILE
    type: string
  - default: oci
    name: FORMAT
    type: string
  - default: "true"
    name: verbose
    type: string
  - default: quay.io/buildah/stable
    name: BUILD_IMAGE
    type: string
  steps:
    script: |
      #!/usr/bin/env bash
      set -eu 

      if [[ "$(params.verbose)" == "true" ]]; then 
        set -x
      fi

      buildah bud --tls-verify=$(params.tlsVerify) \
      --layers  -f $(params.DOCKERFILE) \
      -t $(params.IMAGE) $(params.CONTEXT)
      buildah push --tls-verify=$(params.tlsVerify) $(params.IMAGE)   
    computeResources: {}
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    image: $(params.BUILD_IMAGE)
    name: build-and-push-buildah
    volumeMounts:
    - mountPath: /tekton/home/.docker
      name: kaniko-secret
    - name: varlibc
      mountPath: /var/lib/containers      
    workingDir: $(workspaces.source.path)
  volumes:
  - name: varlibc 
    emptyDir: {}  
  - name: kaniko-secret
    secret:
      items:
      - key: .dockerconfigjson
        path: config.json
      secretName: docker-credentials
  workspaces:
  - name: source
