apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-to-package
spec:
  description: build application and package the files to image
  workspaces:
    - name: source
      description: The git repo that cloned onto the volume backing this workspace
  steps:
    - name: build
      image: maven:3.8-openjdk-11-slim
      workingDir: $(workspaces.source.path)
      script: mvn clean install 
      volumeMounts:
        - name: m2
          mountPath: /root/.m2
  volumes:
    - name: m2
      persistentVolumeClaim:
        claimName: maven-repo