apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: gitlab-trigger-template
spec:
  params:  # 매개변수 정의
  - name: git-revision
  - name: git-repo-url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: trigger-build-and-deploy-pipeline-run-  #  Generate name of PipelineRun
    spec:
      serviceAccountName: tekton-pipeline-sa
      pipelineRef:
        name: build-and-deploy-pipeline 
      params:
        - name: url
          value: $(tt.params.git-repo-url)
        - name: revision
          value: $(tt.params.git-revision)
      workspaces:
        - name: git-source
          persistentVolumeClaim: 
            claimName: my-local-pvc

          
      
