apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn
spec:
  workspaces:
    - name: maven-repo
  params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: mvn
      image:  docker.io/maven:3.6.3-openjdk-8-slim #gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.maven-repo.path)
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(inputs.params.GOALS)"