apiVersion: v1
data:
  policy.csv: |
    p, role:admin-role, applications, *, */*, allow
    p, role:admin-role, projects, get, *, allow
    p, role:admin-role, repositories, get, *, allow
    p, role:admin-role, repositories, create, *, allow
    p, role:admin-role, repositories, update, *, allow
    p, role:admin-role, repositories, delete, *, allow
    p, role:admin-role, clusters, get, *, allow
    p, role:user01, applications, *, user01/*, allow
    p, role:user01, projects, get, user01, allow
    p, role:user01, repositories, get, *, allow
    p, role:user01, clusters, get, *, allow
    g, user00, role:admin-role
    g, user01, role:user-role
  policy.default: role:none
  scopes: '[groups,email]'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, role:admin-role, applications, *, */*, allow\np, role:admin-role, projects, get, *, allow\np, role:admin-role, repositories, get, *, allow\np, role:admin-role, repositories, create, *, allow\np, role:admin-role, repositories, update, *, allow\np, role:admin-role, repositories, delete, *, allow\np, role:admin-role, clusters, get, *, allow\np, role:user-role applications, *, */*, allow\np, role:user-role, projects, get, user01, allow     \np, role:user-role, repositories, get, *, allow     \np, role:user-role, clusters, get, *, allow\np, role:user01, applications, *, user01/*, allow\np, role:user01, projects, get, user01, allow     \np, role:user01, repositories, get, *, allow     \np, role:user01, clusters, get, *, allow\np, role:none, *, *, */*, deny     \ng, user00, role:admin-role   \ng, user01, role:user-role\ng, user02, role:admin\n","policy.default":"role:none","scopes":"[groups,email]"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-11-04T06:55:40Z","labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"68727","uid":"c648f632-9b3f-4d3b-b921-1108416f25bc"}}
  creationTimestamp: "2022-11-04T06:55:40Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd