apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-repo-pv03
  labels:
    type: local
spec:
  capacity: 
    storage: 200Mi
  accessModes:
     - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data03"
