apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: education
spec:
  params:
    - default: 'http://119.81.49.13:7990/scm/isw/sample-service.git'
      description: Git repository url
      name: gitUrl
      type: string
    - default: master
      description: Git revision to check out
      name: gitRevision
      type: string
    - default: src
      description: 'The path to the build context, used by Kaniko - within the workspace'
      name: pathToContext
      type: string
    - default: 'image-registry.apps.openshift-01.knowis.cloud/education/sample:latest'
      description: Image name including repository
      name: IMAGE_NAME
      type: string
    - default: latest
      description: Image tag
      name: imageTag
      type: string
    - default: deployment/sample.yaml
      description: The path to the yaml file to deploy within the git source
      name: pathToYamlFile
      type: string
    - default: sample
      name: APP_NAME
      type: string
  tasks:
    - name: clone-repo
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: deleteExisting
          value: 'true'
        - name: sslVerify
          value: 'false'
        - name: noProxy
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build-maven
      params:
        - name: GOALS
          value:
            - '-B'
            - clean
            - package
            - '-DskipTests'
      runAfter:
        - clone-repo
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
        - name: dockerconfig
          workspace: dockerconfig
    - name: build-and-push
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: IMAGE_TAG
          value: latest
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:ac0b8714cc260c94435cab46fe41b3de0ccbc3d93e38c395fa9d52ac49e521fe
        - name: DOCKERFILE
          value: deployment/Dockerfile
        - name: TLSVERIFY
          value: 'false'
        - name: STORAGE_DRIVER
          value: vfs
      runAfter:
        - build-maven
      taskRef:
        kind: ClusterTask
        name: buildah
      timeout: 2m0s
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
    - name: deploy
      params:
        - name: SCRIPT
          value: |
            echo "deploy to cluster"
            oc delete all --selector app=$(params.APP_NAME) -n education-dev
            ls -al
            oc apply -f  $(params.pathToYamlFile) \
              -n education-dev
      runAfter:
        - build-and-push
      taskRef:
        kind: Task
        name: deploy
      workspaces:
        - name: manifest-dir
          workspace: source
  workspaces:
    - name: source
    - name: dockerconfig
    - name: maven-settings
