apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: github.com
    tekton.dev/git-1: gitlab.com
  name: gitlab-secret
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext username>
  password: <cleartext password>