apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-pipeline
spec:
  workspaces:
    - name: git-source
  params:
    - name: url
      description: Git repository url
    - name: revision
      description: Git revision to check out
      default: "hello"
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
    - name: build-maven
      taskRef:
        name: build-maven
      runAfter:
        - "git-clone"
      workspaces:
        - name: output
          workspace: git-source
    - name: build-and-push
      taskRef:
        name: build-and-push
      runAfter:
        - "build-maven"
      workspaces:
        - name: output
          workspace: git-source
    - name: create-deployment
      params:
      - name: script
        value: |
          kubectl apply -f deployment/deployment.yaml
      runAfter:
      - build-and-push
      taskRef:
        kind: Task
        name: kubernetes-actions
      workspaces:
      - name: manifest-dir
        workspace: git-source