apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-repo-pv06
  labels:
    type: local
spec:
  capacity: 
    storage: 200Mi
  accessModes:
     - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /mnt/data06
