apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-repo-pv07
  labels:
    type: local
spec:
  capacity: 
    storage: 200Mi
  accessModes:
     - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data07
