apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels: 
        app: nodejs-app
    spec:                   
      containers: 
      - name: nodejs-app 
        image: nexweb1/hello:dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 8080
      targetPort: 8080
