apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: nodejs-app
 template:
   metadata:
     labels:
       app: nodejs-app
   spec:                  
     containers:
     - name: nodejs-app
       image: <DOCKERHUB_USER>/<APP_NAME>:latest
       ports:
       - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30001

