apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nodejs-pipelinerun-
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: nodejs-pipeline
  params:
    - name: IMAGE
      value: nexweb1/nodejs-app
    - name: TAG
      value: latest
  workspaces:
    - name: linked-workspace
      persistentVolumeClaim:
        claimName: pipeline-pvc

        