apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata: 
  name: hello-goodbye-pipeline 
spec:
  tasks:
    - name: first-task 
      taskRef:
        name: hello-world
    - name: goodbye-task
      taskRef:
        name: goodbye

        