apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: sonarqube-scanner
spec: 
  description: >-
    이 task는 애플리케이션 소스코드를 정적분석을 수행하기 위해 사용될 수 있습니다.
    SonarQube는 코드베이스의 코드 품질 및 보안을 지속적으로 검사하기 위한 최고의 도구입니다.
  workspaces:
    - name: output 
    - name: sonar-settings 
  params: 
    - name: SONAR_HOST_URL 
      description: 실행중인 sonarqube server 의 url
    - name: SONAR_PROJECT_KEY 
      description: SonarQube Project's unique key
    - name: SONAR_TOKEN
      description: sonarqube login user 
      default: "sqp_f89e9f44277b1e52782fd3c66920704fc441a2ca"
    - name: PROJECT_VERSION 
      description: project version 
      default: "1.0"
  steps: 
    - name: sonar-properties-create 
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      workingDir: $(workspaces.output.path)
      script: | 
        #!/usr/bin/env bash
        replaceValues() {
          filename=$1
          thekey=$2
          newvalue=$3
          if ! grep -R "^[#]*\s*${thekey}=.*" $filename >/dev/null; then
            echo "APPENDING because '${thekey}' not found"
            echo "" >>$filename
            echo "$thekey=$newvalue" >>$filename
          else
            echo "SETTING because '${thekey}' found already"
            sed -ir "s|^[#]*\s*${thekey}=.*|$thekey=$newvalue|" $filename
          fi
        }

        if [[ -f $(workspaces.sonar-settings.path)/sonar-project.properties ]]; then
          echo "using user provided sonar-project.properties file"
          cp -RL $(workspaces.sonar-settings.path)/sonar-project.properties $(workspaces.output.path)/sonar-project.properties
        fi

        if [[ -f $(workspaces.output.path)/sonar-project.properties ]]; then
          if [[ -n "$(params.SONAR_HOST_URL)" ]]; then
            replaceValues $(workspaces.output.path)/sonar-project.properties sonar.host.url $(params.SONAR_HOST_URL)
          fi
          if [[ -n "$(params.SONAR_PROJECT_KEY)" ]]; then
            replaceValues $(workspaces.output.path)/sonar-project.properties sonar.projectKey $(params.SONAR_PROJECT_KEY)
          fi
        else
          touch sonar-project.properties
          echo "sonar.projectKey=$(params.SONAR_PROJECT_KEY)" >> sonar-project.properties
          echo "sonar.host.url=$(params.SONAR_HOST_URL)" >> sonar-project.properties
          echo "sonar.projectVersion=$(params.PROJECT_VERSION)" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties
          echo "sonar.login=$(params.SONAR_TOKEN)" >> sonar-project.properties
          echo "sonar.sources=src/main" >> sonar-project.properties
          echo "sonar.java.binaries=target/classes" >> sonar-project.properties
        fi
        echo "---------------------------"
        cat $(workspaces.output.path)/sonar-project.properties
    - name: sonar-scan 
      image: docker.io/sonarsource/sonar-scanner-cli:4.5
      workingDir: $(workspaces.output.path)
      command:
        - sonar-scanner